spring:
  application:
    name: rest-api-spring-boot
  #profiles:
    #active: test
  datasource:
    url: jdbc:mysql://localhost:3306/demo_spring
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: develop
    password: develop@123
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
springdoc:
  pathsToMath:
  - /api/**/v1/**
  - /api/auth/**
  api-docs:
    path: /api-docs
  swagger-ui:
    use-root-path: true
cors:
  originPatterns: http://localhost:8080,http://localhost:3000
security:
  jwt:
    toke:
      secret-key: 53cct37
      expire-length: 3600000