spring:
  application:
    name: rest-api-spring-boot
  #profiles:
    #active: test
  datasource:
    url: jdbc:mysql://localhost:3306/demo_spring
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: develop
    password: develop@123
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true